# Generated by Django 3.2.9 on 2024-04-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20240428_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('default', 'Default'), ('back', 'Back'), ('front', 'Front'), ('top', 'Top'), ('left', 'Left'), ('right', 'Right'), ('bottom', 'Bottom')], max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'unique_together': {('product', 'image_type')},
            },
        ),
    ]
