# Generated by Django 3.2.9 on 2024-05-01 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='store.product'),
        ),
    ]
