# Generated by Django 3.2.9 on 2024-05-01 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_variation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
