# Generated by Django 3.2.9 on 2024-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_variation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
