# Generated by Django 3.2.9 on 2024-05-03 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20240428_1643'),
        ('store', '0016_variation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.categorymain'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.subcategory'),
        ),
    ]
