# Generated by Django 5.0.6 on 2024-05-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0017_auto_20240503_1109"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
