# Generated by Django 5.0.6 on 2025-03-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
