# Generated by Django 5.0.6 on 2024-05-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_id", models.CharField(max_length=255)),
                ("image_name", models.CharField(max_length=255)),
                ("embedding", models.BinaryField()),
                ("faiss_id", models.IntegerField()),
            ],
        ),
    ]
