# Generated by Django 3.2.9 on 2024-04-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240424_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(default='webapp/assets/img/user/user.png', max_length=250),
        ),
    ]
