# Generated by Django 3.2.9 on 2024-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(default='webapp/assets/images/user/user.png', max_length=500),
        ),
    ]
