# Generated by Django 3.2.9 on 2024-04-30 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_color'),
        ('category', '0004_auto_20240428_1643'),
        ('accounts', '0008_auto_20240428_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('cart', 'Cart'), ('pay', 'Pay')], max_length=10)),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_events', to='category.categorymain')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_events', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event User',
                'verbose_name_plural': 'Event Users',
            },
        ),
    ]
