# Generated by Django 3.2.9 on 2024-04-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_eventuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
