# Generated by Django 3.2.9 on 2024-05-01 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20240428_1643'),
        ('accounts', '0010_eventuser_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_events', to='category.subcategory'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_events', to='category.categorymain'),
        ),
    ]
