# Generated by Django 3.2.9 on 2024-05-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20240501_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='price',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='sub_category',
        ),
    ]
