# Generated by Django 3.2.9 on 2024-05-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20240505_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, default='other', max_length=100),
        ),
    ]
