# Generated by Django 3.2.9 on 2024-05-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userprofile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
