# Generated by Django 3.2.9 on 2024-05-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_eventuser_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
