# Generated by Django 3.2.9 on 2024-05-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_account_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_login',
        ),
    ]
