# Generated by Django 5.0.6 on 2024-05-15 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_account_is_login"),
        ("store", "0017_auto_20240503_1109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventuser",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("cart", "Cart"),
                    ("pay", "Pay"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="eventuser",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_events",
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="eventuser",
            name="rating",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
