# Generated by Django 5.0.6 on 2024-05-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_alter_orderproduct_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Ready to ship", "Ready to ship"),
                    ("On shipping", "On shipping"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                    ("Return", "Return"),
                    ("Refunded", "Refunded"),
                ],
                default="Accepted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="orders.payment",
            ),
        ),
    ]
