# Generated by Django 5.0.6 on 2024-05-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_alter_order_order_status_alter_order_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="orders.payment",
            ),
        ),
    ]
