# Generated by Django 5.0.6 on 2024-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_alter_order_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Ready to ship", "Ready to ship"),
                    ("On shipping", "On shipping"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                    ("Return", "Return"),
                ],
                default="Accepted",
                max_length=50,
            ),
        ),
    ]
