# Generated by Django 5.0.6 on 2024-05-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_alter_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_view",
            field=models.BooleanField(default=True),
        ),
    ]
